name: Build and Deploy Plugins

on:
  schedule:
    - cron: '0 3 */7 * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libncurses5-dev gawk git gettext unzip file libssl-dev wget python3 python3-pip
          pip3 install -U requests pyyaml

      - name: Build x86_64 Plugins
        run: bash scripts/build_x86_64.sh

      - name: Build aarch64 Plugins
        run: bash scripts/build_aarch64.sh

      - name: Clean old packages
        run: bash scripts/clean_old.sh

      - name: Generate index.html
        run: bash scripts/gen_index.sh

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ipk








