name: Build and Deploy Plugins

on:
  schedule:
    - cron: '0 3 */7 * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libncurses5-dev gawk git gettext unzip file libssl-dev wget python3 python3-pip
        pip3 install -U requests pyyaml

    - name: Build plugins for x86_64
      run: |
        chmod +x scripts/build_x86_64.sh
        ./scripts/build_x86_64.sh || (echo "Retrying..." && sleep 10 && ./scripts/build_x86_64.sh)

    # - name: Build plugins for aarch64_cortex-a53
    #   run: |
    #     chmod +x scripts/build_aarch64.sh
    #     ./scripts/build_aarch64.sh

    - name: Clean old .ipk files
      run: |
        chmod +x scripts/clean_old.sh
        ./scripts/clean_old.sh

    - name: Generate index.html
      run: python3 scripts/gen_index.py

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./ipk







