name: Build OpenWrt Plugin Repo

on:
  schedule:
    - cron: '0 2 */7 * *'  # 每 7 天 UTC 时间 2 点执行
  workflow_dispatch:       # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repo
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y gzip coreutils

      - name: Build Packages.gz
        run: bash scripts/build_packages.sh

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          files: |
            ipk/**/Packages.gz
            ipk/**/*.ipk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

