name: Build and Clean Plugins

on:
  schedule:
    - cron: '0 3 */7 * *'  # 每7天凌晨3点触发一次
  workflow_dispatch:       # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y curl jq # 你实际需要什么依赖这里加

    - name: Build plugins for x86_64
      run: |
        echo "这里写你的 x86_64 编译和打包脚本"
        # 例如：./scripts/build_x86_64.sh

    - name: Build plugins for aarch64_cortex-a53
      run: |
        echo "这里写你的 aarch64_cortex-a53 编译和打包脚本"
        # 例如：./scripts/build_aarch64.sh

    - name: Upload .ipk files to GitHub Releases or GitHub Pages
      run: |
        echo "这里写你的上传脚本，比如使用 gh release 或上传到 pages"
        # 例如：./scripts/upload.sh

    - name: Run clean_old.sh to remove old versions
      run: |
        chmod +x ./scripts/clean_old.sh
        ./scripts/clean_old.sh


